### PR TITLE
Theme git-gutter faces

### PR DESCRIPTION
**Pull request by justbur**

### CODE REVIEW

**Comment by jasonm23** [comment]
Thanks @justbur please post a screen grab

**Comment by justbur** [comment]
git-gutter

**Comment by justbur** [comment]
by the way, the diff-hl faces aren't working for me, which is why I switched.

**Comment by jasonm23** [comment]
Ok thank you.

I have git gutter working ok with Darktooth without specific faces set, so I won't be happy with them changing.

Middle of the night here in Singapore so I will get a better look at this tomorrow.

**Comment by justbur** [comment]
I think it might be unclear what I was saying. The diff-hl fringe indicators don't show up for me in emacs 25 (but they do in emacs 24.5 for some reason). The git-gutter ones work fine but the default colors clashed with the theme, which is why I submitted this pr.

**Pull request closed without merging**
