### PR TITLE
change sp-show-pair-match-face

### PR DESCRIPTION
**Pull request by bb2020**
it is really hard to distinguish from the background

### CODE REVIEW

**Comment by jasonm23** [comment]
Please add a before / after screen grab

**Comment by bb2020** [comment]
before


after

**Comment by jasonm23** [comment]
Sorry rejecting.

**Comment by Poorchop** [comment]
@jasonm23 Would you consider another color? I do agree that it is pretty hard to distinguish from the background as it currently stands.

**Comment by jasonm23** [comment]
One of the blues shows for me, not sure why.

**Comment by bb2020** [comment]
maybe you have show-paren-mode enabled?

**Comment by jasonm23** [comment]
I believe so.  The two should match.

**Comment by bb2020** [comment]
However `sp-show-pair-enclosing` is also using the same face with `show-paren-match`. I think `sp-show-pair-enclosing` and `sp-show-pair-match-face` should differ.

**Comment by jasonm23** [comment]
You can propose a change with image grabs, but please note that the tone of the theme is not bright purple friendly.  :)

**Comment by bb2020** [comment]
It was faded purple (:
What about faded orange. Looks a bit like mismatch face though

faded orange
screen shot 2016-05-11 at 7 28 09 pm

mismatch (natural-red)
screen shot 2016-05-11 at 7 28 11 pm

**Comment by Poorchop** [comment]
> One of the blues shows for me

That's how I ported it over to the other themes I made. I think I took some liberty here in the case of the Brackets theme and sampled directly from emacs, probably because I had the same issue as bb2020 when I used the color specified in the actual template. I have the color set to `#076679` and I think one of the blues would look best too.

**Comment by jasonm23** [comment]
Blues are preferable for this.

Anything along the lines of the predefined delimiter colors. Tints are ok.  Just name it in line with the other colors.

**Pull request closed without merging**
