### PR TITLE
Add ERC support

### PR DESCRIPTION
**Pull request by galaunay**
Add support for ERC.

Some screenshots below:
- Test in #darktooth channel
erc1
- #python channel (#emacs was merely empty that day):
erc2

- For comparison, the #python channel before customization:
erc3

### CODE REVIEW

**Comment by jasonm23** [comment]
LGTM! 👍  please resolve the rebase on master, and force push to your branch.

**Comment by galaunay** [comment]
Is it what you needed ?

Please note that I am not a ERC user for a long time, so some faces may not be optimal.
I guess it is still a good first step.

**Comment by jasonm23** [comment]
Thank you - just needed to fix the merge conflict.

**Comment by dieggsy** [comment]
Is there a missing parens one of these commits? `M-x check-parens` is showing `Unmached bracket or quote` on current master.

**Comment by jasonm23** [comment]
Please fix. You'll have to submit a new pr if this isn't working.  I'll roll the repo back

**Comment by jasonm23** [comment]
It's rolled back. 

I'm going to review.

**Comment by jasonm23** [comment]
Pushed as 0.3.10 - ae14a9b

**Comment by jasonm23** [comment]
FYI the FORM for `autothemer-deftheme` was closed at your eldoc theme definition, just an extra parenthesis.

Ironic since it was eldoc that allowed me to find the problem 🤓

**Comment by jasonm23** [comment]
@galaunay & @dieggsy  thanks for the help on getting ERC support added.

Glad it's now done 👍

**Comment by galaunay** [comment]
Sorry about the parenthesis.
I went through the merging a little bit to fast I guess...

**Comment by jasonm23** [comment]
Thank you @galaunay don't feel bad about it.  I appreciate your help.

**Pull request merged**
