### PR TITLE
Added org-document faces 

### LINKED ISSUE #43: Darktooth Does Not Explicitly Set org-document-title
Hi,

Today, I found that on my installation of Emacs the font for org-document-title was a pretty dark blue on Darktooth's dark background.  In a default Emacs session (-Q) this is not the case.

This time, I could hunt the problem down to zenburn theme being installed.  It just sat there in `~/.emacs.d/elpa/zenburn-theme....`. I do not load it explicitly, but it is listed in `package-selected-packages` in my custom.el. If I remove it from that variable, everything works.

My guess here is, that themes will set faces when being loaded even if they are not used.  Mind that I am not really familiar with the themes machinery in Emacs.

I'd like to clarify in this ticket if Darktooth should set more faces explicitly to generate reproducible behavior. If yes, I'll happily provide a PR for this face (and others when I come across them).

Best regards,
stefan

### PR DESCRIPTION
**Pull request by ska2342**
fixes #43 

* org-document-title darktooth-bright_cyan, bold
  The other headings also use faces from the darktooth-bright
  family. Cyan was not yet taken and stands out. Using bold instead of
  larger font.
* org-document-info darktooth-identifiers-7
  Using font which is suggested by autothemer-generate-templates
* org-document-info-keyword darktooth-light2
  The face used to highlight the special document keywords TITLE,
  AUTHOR, DATE, and EMAIL. Default is inherited from 'shadow which is
  grey70 (#b3b3b3). darktooth-light2 is very close to that.

### CODE REVIEW

**Comment by ska2342** [comment]
## Screenshot of new faces in Emacs 24

grafik

## Screenshot in Emacs 25.1 *without* changes:

grafik

## Screenshot in Emacs 25.1 *with* changes:

grafik

**Comment by jasonm23** [comment]
LGTM

**Comment by jasonm23** [comment]
Thank you Stefan

**Comment by dieggsy** [comment]
Awesome!

**Pull request merged**
