### PR TITLE
Add tab-bar and tab-line mode support (emacs 27) 

### PR DESCRIPTION
**Pull request by dalanicolai**

### CODE REVIEW

**Comment by jasonm23** [comment]
Thank you for your contribution.

Please provide a before and after screen shot in this conversation, to complete review and merge.

**Comment by dalanicolai** [comment]
So obviously it is about the tab bar at the top of the screen...

before
Screenshot from 2020-12-12 16-27-32

after
Screenshot from 2020-12-12 16-28-26

**Comment by dieggsy** [comment]
I think you might make the background same color as the mode-line or something like that so it's distinguishable?

**Comment by dalanicolai** [comment]
Yes true. But this is the before and after on my Spacemacs (using [centaur-tabs](https://github.com/ema2159/centaur-tabs))

before
Screenshot from 2020-12-13 05-03-13

after
Screenshot from 2020-12-13 05-01-38

As you can see, by default, the tabs take the color of the theme but the tab bar does not (I did not realize that this behavior is due to the Centaur tabs package.)
So this PR makes it look much better.

You are free to choose a different color to make it distinguishable, but actually the tabs themselves are already a distinguishable color (in Spacemacs). For Emacs it is fine if the bar is indistinguishable, but you could give it a different color. But at least I do think that the theme should modify the color of the tab bar, instead of keeping it the default color.

**Comment by jasonm23** [comment]
Thanks for the input @dieggsy 

Appreciate the contribution @dalanicolai 

Happy to merge.

**Pull request merged**
