### PR TITLE
Prevent underlining of annotations

### PR DESCRIPTION
**Pull request by j0ni**
I hope this isn't too previous of me. I added a line to this theme to make it more pleasing to me now that emacs 30 seems to be adding an underline to this (or maybe a related/parent face) which makes the minibuffer content which the theme doesn't touch look wrong (to me).

The only impact I see is for marginalia-mode, though I expect there are other implications. For one thing I use minibuffer completion (using vertico) for everything including where most other folk use something like company-mode. I have no idea if that is impacted by this change.

Anyways, I had not initially intended to PR this, but on reflection it seems like offering it up is not a bad idea - I won't be offended if you would rather leave it as is, or even make a different decision about styling.

### CODE REVIEW

**Comment by jasonm23** [comment]
Thank you for the contribution. For all PRs, before and after screengrabs
are required for all variants of the theme

As Darktooth supports earlier versions of Emacs, screenshots are also
required for versions 28.x & 29.x (at minimum).

**Comment by j0ni** [comment]
Ah so, entirely fair.

I will close this for now and come back if and when I have time to do that for all 3 versions.

**Comment by jasonm23** [comment]
Probably better if it's left open.  To avoid duplicates etc

**Comment by jasonm23** [comment]
Checked, merging.

**Comment by jasonm23** [comment]
ac7c3a2

**Pull request closed without merging**
