### PR TITLE
Add smart-mode-line support

### PR DESCRIPTION
**Pull request by manuel-uberti**
I added support for @malabarba https://github.com/Malabarba/smart-mode-line

### CODE REVIEW

**Comment by Malabarba** [comment]
darktooth is my theme of choice, so it would be very nice to have this!

**Comment by jasonm23** [comment]
Looks good to me.

**Comment by Malabarba** [comment]
Now that I had a chance to see this, I think it might be a bit colorless.
Here's what it looks like on my screen. In particular, the `darktooth-dark1` color makes the filename very hard to read.
screenshot-2015-10-16--221341

Purely for context, here's what the sml `respectful` theme looked like before
screenshot-2015-10-16--221816

**Comment by jasonm23** [comment]
I'll revert this for now. It can be revised

**Comment by jasonm23** [comment]
Done.  @manuel-uberti please consider reworking the color choices.

**Comment by jasonm23** [comment]
MELPA now has the reverted version

**Comment by manuel-uberti** [comment]
Sure thing, I'll rework the colors. Thanks for the update.

**Pull request merged**
