### PR TITLE
Add full magit support

### PR DESCRIPTION
**Pull request by Olivia5k**
Add face definitions for all the faces that the latest version of
magit defines.

I was pretty liberal with using bolds for labels and label-like faces.
If this feels a bit of for the darktooth style, I can unbold most of
them!

### CODE REVIEW

**Comment by jasonm23** [comment]
Thanks I'll give it a look today.

**Comment by manuel-uberti** [comment]
Oh yes please. :+1:

**Comment by jasonm23** [comment]
Looks ok, I may refine it after I've dogfooded it sufficiently (dark tooth is my daily theme since its creation.)

**Comment by manuel-uberti** [comment]
Looks beautiful, thank you both.

**Comment by Olivia5k** [comment]
Please do! I did my best to approximate the _feel_ of the colorscheme to make it match the other modes too. darktooth is my day-to-day scheme as well! :)

Cheers to both of you! :dancer:

**Comment by jasonm23** [comment]
The only thing I want to change at this point is the tag name in the status view. Other than that, I have no complaints with it whatsoever.

**Comment by jasonm23** [comment]
Made a few changes, they'll be available from MELPA now.

**Pull request merged**
