### PR TITLE
Add elixir-mode support

### PR DESCRIPTION
**Pull request by chouzan**
I added [elixir-mode](https://github.com/elixir-lang/emacs-elixir) support.

### CODE REVIEW

**Comment by jasonm23** [comment]
Thank you!

please add a screenshot to this comment thread

**Comment by chouzan** [comment]
Right. So, elixir-mode add two custom face, for module `attribute` and tuple `atom`. I just reuse the appropriate default font-lock-face. Here before the theme support:
image

and here after:
image

**Comment by jasonm23** [comment]
Ok vast improvement. 

Thank you.

**Comment by jasonm23** [comment]
Go ahead and increment the patch number on the version.

Then I'll merge it.

**Comment by chouzan** [comment]
@jasonm23 version bumped 😄

**Comment by jasonm23** [comment]
👍

**Pull request merged**
